config/routes.rb
Rails.application.routes.draw do
  resources :concerts do
  # /concerts
    resources :comments
  # Nested resource which means:  /concerts/:concerts_id/comments
  end 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :concert
end

app/models/concert.rb
class Concert < ApplicationRecord
	has_many :comments 
	
	validates :artist, presence: true
	validates :venue, presence: true
	validates :city, presence: true
	validates :date, presence: true
	validates :description, presence: true
	validates :price, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def index
		@concert = Concert.find params[:concert_id]
		@comments = @concert.comments
	end

	def new 
		# byebug
		@concert = Concert.find params[:concert_id]
		@comment = @concert.comments.new

	end


	def create
		@concert = Concert.find params[:concert_id]
		@comment = @concert.comments.new comment_params

		if @comment.save
			flash[:notice] = "Comment created sucesfully"
			# redirect_to concert_comments_path(@concert)
			redirect_to "concerts/#{@concert.id}"
			# redirect_to concert_path(@comment)

		else
			flash.now[:alert] = "Problem with the comment"
			@errors = @comment.errors.full_messages
			render 'new'
		end
	end



	private
	
	def comment_params
		 params.require(:comment).permit(:user_name, :comment)
	end



end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_action :set_concert, only: [:show, :edit, :update, :destroy]

  # GET /concerts
  # GET /concerts.json
  def index
    @concerts = Concert.all
  end

  # GET /concerts/1
  # GET /concerts/1.json
  def show
  end

  # GET /concerts/new
  def new
    @concert = Concert.new
  end

  # GET /concerts/1/edit
  def edit
  end

  # POST /concerts
  # POST /concerts.json
  def create
    @concert = Concert.new(concert_params)

    respond_to do |format|
      if @concert.save
        format.html { redirect_to @concert, notice: 'Concert was successfully created.' }
        format.json { render :show, status: :created, location: @concert }
      else
        format.html { render :new }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concerts/1
  # PATCH/PUT /concerts/1.json
  def update
    respond_to do |format|
      if @concert.update(concert_params)
        format.html { redirect_to @concert, notice: 'Concert was successfully updated.' }
        format.json { render :show, status: :ok, location: @concert }
      else
        format.html { render :edit }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concerts/1
  # DELETE /concerts/1.json
  def destroy
    @concert.destroy
    respond_to do |format|
      format.html { redirect_to concerts_url, notice: 'Concert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concert
      @concert = Concert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def concert_params
      params.require(:concert).permit(:artist, :venue, :city, :date, :description, :price, :done_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/views/comments/new.html.erb
<h1>Type your comment here! </h1>


<%= form_for [@concert, @comment] do |f| %> 
<!-- Form for with two instance variables: is because in routes comments is nested inside concert url (nested resource.) -->

  <%= f.label :user_name %>
  <%= f.text_field :user_name %>
  <br>
  <%= f.label :comment %>
	<%= f.text_field :comment %>

	<%= f.submit "Submit" %>

<% end %>

app/views/concerts/_form.html.erb
<%= form_for(concert) do |f| %>
  <% if concert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(concert.errors.count, "error") %> prohibited this concert from being saved:</h2>

      <ul>
      <% concert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :artist %>
    <%= f.text_field :artist %>
  </div>

  <div class="field">
    <%= f.label :venue %>
    <%= f.text_field :venue %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :done_at %>
    <%= f.datetime_select :done_at %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/concerts/edit.html.erb
<h1>Editing Concert</h1>

<%= render 'form', concert: @concert %>

<%= link_to 'Show', @concert %> |
<%= link_to 'Back', concerts_path %>

app/views/concerts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Concerts</h1>

<table>
  <thead>
    <tr>
      <th>Artist</th>
      <th>Venue</th>
      <th>City</th>
      <th>Date</th>
      <th>Description</th>
      <th>Price</th>
      <th>Done at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concerts.each do |concert| %>
      <tr>
        <td><%= concert.artist %></td>
        <td><%= concert.venue %></td>
        <td><%= concert.city %></td>
        <td><%= concert.date %></td>
        <td><%= concert.description %></td>
        <td><%= concert.price %></td>
        <td><%= concert.done_at %></td>
        <td><%= link_to 'Show', concert %></td>
        
        <!-- <td><%= link_to 'Destroy', concert, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Concert', new_concert_path %>

app/views/concerts/new.html.erb
<h1>New Concert</h1>

<%= render 'form', concert: @concert %>

<%= link_to 'Back', concerts_path %>

app/views/concerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Artist:</strong>
  <%= @concert.artist %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @concert.venue %>
</p>

<p>
  <strong>City:</strong>
  <%= @concert.city %>
</p>

<p>
  <strong>Date:</strong>
  <%= @concert.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @concert.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @concert.price %>
</p>

<p>
  <strong>Done at:</strong>
  <%= @concert.done_at %>
</p>

<p>

<strong>COMENTARIOS:</strong> 




<!-- <%= @concert.inspect%> => RESULT FROM ABOVE INSPECT #<Concert id: 1, artist: "Luke", venue: "Razzmatazz", city: "Barcelona", date: "2016-08-17", description: "an awesome party", price: 15, done_at: nil, created_at: "2016-11-13 17:16:49", updated_at: "2016-11-13 17:16:49"> -->



<!--<%= @concert.comments.inspect%> => RESULT FROM ABOVE INSPECT: #<ActiveRecord::Associations::CollectionProxy []> -->
<!-- where The collection proxy and the [] tells me that it's an array -->



<% @concert.comments.each do |comment| %>
<p><%= comment.comment %></p>
<% end %>

</p>

<%= link_to 'Back', concerts_path %>
<%= link_to 'Add comment', new_concert_comment_path(@concert) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicConcert</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header></header>
    <%= yield %>

    <footer></footer>
  </body>
</html>